name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: unfor19/install-aws-cli-action@master
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run tests
      run: |
        sbt coverage +test coverageReport coverageAggregate
    - name: Run aws
      run: aws --version
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: true        
